### ISSUE TITLE
defdelegate not supported inside protocols

### ISSUE THREAD

**Issue by dmorneau** [tompave/fun_with_flags#104]
FunWithFlags is using `defdelegate` within a `defprotocol` block, which is not officially supported and will break in a future Elixir release. See: https://github.com/elixir-lang/elixir/issues/10877#issuecomment-813266478

**Comment by kelvinst** [comment]
I can work on PR for this if no one else is interested 😀

**Comment by tompave** [comment]
Ah, nice catch, thank you.
Yes, I'd welcome a PR for this. 👍

**Comment by tompave** [comment]
@kelvinst I think it would be nice to simplify this. We don't really need to go through the `Actor` protocol to call that function.

I suppose we can update where `Actor.score/2` is invoked to call it directly on the `Actor.Percentage` module. And update the documentation.

**Comment by kelvinst** [comment]
Yep, that was what I was planning to do. Will probably do it tonight, but if want to do it yourself, please go ahead.

**Comment by tompave** [comment]
I'd welcome a PR :-)

**Comment by tompave** [comment]
@dmorneau apologies for the wait. Here is the release: https://hex.pm/packages/fun_with_flags/1.7.0

**Comment by dmorneau** [comment]
Thank you! This library has been super useful for my team 😀
