### ISSUE TITLE
FunWithFlags.Supervisor not loaded when using mix releases

### ISSUE THREAD

**Issue by dvic** [tompave/fun_with_flags#106]
In order to make the use of the new `FunWithFlags.Supervisor`, I added `runtime: false` to both `fun_with_flags` and `fun_with_flags_ui`, but it failed to run in production with an error that `FunWithFlags.Supervisor` is not found.

The following seems to fix the problem:

```elixir
      releases: [
        myapp: [
          applications: [fun_with_flags: :load, fun_with_flags_ui: :load]
        ]
      ]
```

Is there something I'm missing or should the above be added to the docs for the people who are using `mix release` to package their app?

**Comment by dvic** [comment]
In addition I also had to add the following to make dialyzer work:

```elixir
      dialyzer: [
        plt_add_apps: [:fun_with_flags],
      ]
```

**Comment by tompave** [comment]
Hey there, thank you for using the package and for reporting the issue.

I must admit that I'm not very familiar with how this setup would interact with releases. I haven't used them a lot, personally.

If there is a way to make this better, either with code changes or with better documentation, we should! Do you have any suggestion in mind? My only request is to avoid breaking changes.

**Comment by dvic** [comment]
I'm no expert on this topic either, but the above did work for me (both for releases and dialyzer), so I could open a PR and add this to the relevant section.

If I may add my two cents on the breaking changes: I believe there is a trend in the ecosystem where more and more libraries move to the 'you need to add it to the supervisor tree yourself' approach. One example of this is `goth`: https://github.com/peburrows/goth#upgrading-from-goth--13 (a popular google auth library). So you might want to reconsider making this the default way forward for this library, especially if there might be some problems with *not* putting it in the supervisor tree yourself. Of course you could release it as `2.0` to indicate the breaking change.

**Comment by tompave** [comment]
I believe that this has been resolved in the last couple of released versions, because of the changes in how config is handled.
