### ISSUE TITLE
Store provider is set on compile time

### ISSUE THREAD

**Issue by andreasknoepfle** [tompave/fun_with_flags#114]
Hello 👋 

when working with `FunWithFlags` in our test suite we noticed that we have to recompile the `fun_with_flags` dependency every time we changed the config around the storage provider (we wanted to simply disable the `cache` in the test environment). 
```
 ** (exit) exited in: GenServer.call(FunWithFlags.Store.Cache, {:put, %FunWithFlags.Flag{gates: [%FunWithFlags.Gate{enabled: true, for: "user:...", type: :actor}], name: :foo}}, 5000)
 ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't starte
```

This happens, because the config is stored in a module variable:
https://github.com/tompave/fun_with_flags/blob/master/lib/fun_with_flags.ex#L30

So when we changed the config to disable caching, it would still use the `StoreProvider` instead of the `SimpleStoreProvider`, but with the cache process not started.

Would it make sense to move this call from a module variable `@store` into a function `store()`, so that the config is still changeable without needing to recompile the project? 

I can happily help out and open a PR if you agree :)

Also thank you for creating this great project btw 💚. It really is a joy to use and helps us a great deal in our workflows. 

Cheers 
Andi

**Comment by tompave** [comment]
Hello, thank you for using the package and for the kind words. :-)

This is explained in the readme: https://github.com/tompave/fun_with_flags#configuration-changes-have-no-effect-in-mix_envdev
It has also come up a few times in other issues.

The TL;DR is that it's for performance reasons. I want this package to be fast to call even in very hot code paths, and going through the application env will introduce another ETS lookup.

**Comment by tompave** [comment]
This is being addressed by using `Application.compile_env/3` in https://github.com/tompave/fun_with_flags/pull/116.
