### ISSUE TITLE
Changing `ecto_table_name` config requires recompile

### ISSUE THREAD

**Issue by micahbf** [tompave/fun_with_flags#123]
The `ecto_table_name` config is evaluated at compile time here: https://github.com/tompave/fun_with_flags/blob/master/lib/fun_with_flags/store/persistent/ecto/record.ex#L11

However this uses `Application.get_env` in `Config.ecto_table_name` by way of `Config.persistence_config`.

The result is that changing the `:fun_with_flags, :persistence, :ecto_table_name` config has no effect unless FunWithFlags is recompiled.

I would expect FunWithFlags to reflect the config changes, as it does with the rest of the persistence settings.

I found some info [here](https://stackoverflow.com/questions/40687186/how-can-you-dynamically-set-a-schema-table-name-for-a-ecto-model) that shows how to set a table name at runtime for an existing schema (with `Ecto.put_meta/2`).

If this sounds right, I could put together a PR.

**Comment by tompave** [comment]
Thanks for opening this issue.
I think that this is something that should have been fixed when I worked on this:
https://github.com/tompave/fun_with_flags/blob/2b97162ebef2a40f09fb56a22dd9093a00a860ba/lib/fun_with_flags/config.ex#L67
`Application.compile_env` is probably the way to go in this case.

If you want to sent a PR that adopts that pattern, I'd be happy to accept it.

**Comment by tompave** [comment]
Basically this:
```elixir
  schema Config.ecto_table_name() do
```

should possibly become:

```elixir
  schema Config.ecto_table_name_determined_at_compile_time() do
```

**Comment by tompave** [comment]
This was addressed with https://github.com/tompave/fun_with_flags/pull/130.

**Comment by micahbf** [comment]
Awesome! Sorry I didn't follow up myself.
