### ISSUE TITLE
The module `FunWithFlags.Supervisor` was given as a child to a supervisor but it does not exist

### ISSUE THREAD

**Issue by RealVidy** [tompave/fun_with_flags#133]
I run FunWithFlags with `runtime: false` in my `mix.exs` so I can start it manually in my supervision tree because I use `Phoenix.PubSub`.

I have added `FunWithFlags.Supervisor` to my supervision tree and it works just fine in dev. In prod however, I get `The module FunWithFlags.Supervisor was given as a child to a supervisor but it does not exist` and I am not sure why.

I am on version 1.8.1 of the library and I use `fun_with_flags_ui` 0.8 which is also configured with `runtime: false`.

What might be the issue?

**Comment by tompave** [comment]
Thank you for using the library and for reporting the issue.

That sounds odd. Have you tried to delete and recompile all build artifacts?
Also, what do you mean by "dev" and "prod"? Would that be `Mix.env()` or are you using a release?

**Comment by tompave** [comment]
Also, does it still happen if you choose the other option outlined in the readme? https://github.com/tompave/fun_with_flags#application-start-behaviour

**Comment by RealVidy** [comment]
I did recompile everything at the time, which didn't help, and I do use releases so that's what I meant by dev vs prod. Sorry I wasn't clear about that, I didn't realize using releases would impact the way dependencies are included in the app.

I found a way to make it work, but there were two issues I had to fix and one of them is a bit of a hack.

First, the `included_application` option described in the doc was indeed the way to go for me:
````
included_applications: [<other_apps>,  :fun_with_flags]
```
`:fun_with_flags_ui` should not be in there though, otherwise It fails.

The other issue I had was that when `:fun_with_flags_ui` was in my deps, it would trigger this error: `(Mix) :fun_with_flags is listed both as a regular application and as an included application`.

I understood it to mean that `:fun_with_flags_ui` adds `:fun_with_flags` to `:applications` on its own so I forked fun_with_flags_ui and changed the fun_with_flags dependency to `{:fun_with_flags, "~> 1.8", runtime: false}`. That's the hack I was talking about.

Now it all works great with a prod release but I'd be happy to help find a better way to fix this issue. Let me know if I can help :)

Thanks for your help!

**Comment by tompave** [comment]
It's interesting that you need to add `runtime: false` to the Mix deps of the UI package. 🤔 

Have you tried to define it in your application as:
```elixir
{:fun_with_flags_ui, "~> 0.8", runtime: false}
```

**Comment by RealVidy** [comment]
I did try most possible combinations and I believe this one failed with an error akin to `FunWithFlags.UI.Router module could not be found`. For some reason, `runtime: false` seems to remove the dependency from my build entirely 🤷 .

I cannot really test this again because the only way I have found to reproduce is to deploy my code, which would break prod :/

**Comment by tompave** [comment]
Ok, thank you.

**Comment by tompave** [comment]
I see, thank you @dhaspden.
I would welcome PRs that update the instructions in the `README.md` to clarify how to configure this correctly in releases. I suppose we can also add a wiki page, if it ends up being too long.

**Comment by jmillxyz** [comment]
@dhaspden would you mind elaborating on your solution? I'm running into this problem but I'm not familiar with `releases/0`, and my search of the docs hasn't helped thus far.

**Comment by zaid** [comment]
@jmillxyz I got it working by marking the two dependencies with `runtime: false` (attempt #1 in your example) and making the following changes to the `releases` function in `mix.exs`:

```elixir
defp releases() do
  [
    my_app: [
      applications: [
        fun_with_flags: :load,
        fun_with_flags_ui: :load
      ]
   ]
]
end
```
I'll create a pull request to update the documentation shortly.

**Comment by tompave** [comment]
Thank you for everyone's efforts in investigating and documenting this.

I would appreciate it if other people who've come across this problem could have a look at the documentation PR and express feedback.
