### ISSUE TITLE
Support redis sentinel

### ISSUE THREAD

**Issue by ByeongUkChoi** [tompave/fun_with_flags#136]
How about support redis `sentinel`?
When using redis, there is an error because of the @default_redis_config.host and port.
https://github.com/whatyouhide/redix/blob/641d6667809d0a932942a8c95fdc19e862a0858e/lib/redix/start_options.ex#L84
I think need this pr https://github.com/tompave/fun_with_flags/pull/107

**Comment by tompave** [comment]
Thank you for reporting this. I've merged that PR. It's on master for now, and it will be part of the next release.
