### ISSUE TITLE
Warnings when FWF is used with ecto

### ISSUE THREAD

**Issue by rewritten** [tompave/fun_with_flags#138]
Hi :)

A bit related to #137 but it's probably independent from it.

When adding both FWF and Ecto as dependencies, the log starts being polluted with a lot of messages like 

```
warning: Ecto.Changeset.cast/3 defined in application :ecto is used by the current 
application but the current application does not depend on :ecto. To fix this, you 
must do one of:
  1. If :ecto is part of Erlang/Elixir, you must include it under :extra_applications 
     inside "def application" in your mix.exs
  3. If :ecto is a dependency, make sure it is listed under "def deps" in your mix.exs
  4. In case you don't want to add a requirement to :ecto, you may optionally skip this 
     warning by adding [xref: [exclude: [Ecto.Changeset]]] to your "def project" in 
     mix.exs
  lib/fun_with_flags/store/persistent/ecto/record.ex:22: FunWithFlags.Store.Persistent.Ecto.Record.changeset/2
```

I'm not sure if this can be solved, but clearly FWF cannot _depend_ on Ecto, but at the same time the app depends on ecto itself.

Maybe adding those ref excludes in FWF `def project()`  would do?

I will attempt to use a local fork with these changes, but I'm not sure how we can actually test them in isolation.

**Comment by tompave** [comment]
Closing as it's possibly the same problem described in https://github.com/tompave/fun_with_flags/issues/137. We can reopen this if they turn out to be distinct.

**Comment by rewritten** [comment]
Indeed it's the same problem :)
