### ISSUE TITLE
Don't require compile-time configuration

### ISSUE THREAD

**Issue by zachallaun** [tompave/fun_with_flags#153]
*Edit:* I did some poking around and am seeing some places I missed initially where FunWithFlags is doing various dependency injection in a way that may indeed require compile-time config. If that's the case, this issue can definitely be closed.

Unless I'm much mistaken, FunWithFlags currently requires that configuration occurs at compile-time, i.e. in `config.exs`. There is a [growing trend](https://felt.com/blog/elixir-configuration) of moving away from compile-time config and to runtime config using `runtime.exs`, but FunWithFlags ~~uses `Application.compile_env(...)` to handle configuration, which doesn't have access to runtime configuration~~ (edit: I don't think this is correct, but there seem to be other issues with using runtime configuration.).

Configuration information is currently stored in module attributes, but it would not be a difficult refactor to store this information in a runtime-accessible location. Many libraries choose to just use the app env at runtime, but `:persistent_term` could be used for very fast lookup. Alternatively, Oban [uses `Registry`](https://github.com/sorentwo/oban/blob/v2.13.6/lib/oban/registry.ex#L17). Either of these options would provide more flexibility and less likelihood of running into strange errors about compile-and-runtime config being different.

I'll acknowledge that there will be some performance penalty vs. using module attributes known at compile-time; perhaps that penalty is enough for this to be a non-starter. The prevalence of runtime config elsewhere in the ecosystem makes me doubt that the overhead is significant, however.

**Comment by tompave** [comment]
Hey there, thank you for using the library!

Yes, FWF relies on config at compile time, and stores some stuff in module attributes for performance reasons. It used to be worse, but today it uses `Application.compile_env` exclusively, and any people are properly warned of any issues with their setups.

The topic has been discussed several times. For reference: https://github.com/tompave/fun_with_flags/issues?q=is%3Aissue+config+compile+is%3Aclosed

As you mentioned in your edit to your own message, this issue can be closed.
