### ISSUE TITLE
Use case: flag <-> group relationship 

### ISSUE THREAD

**Issue by ghenry** [tompave/fun_with_flags#155]
Hi all,

I'm looking to create a group name that relates to a subscription plan. That plan has certain features enabled.

Is there a way to check if "premium" feature is enabled and the lib returns true if the actor is part of the "premium" group?

Not used in anger yet, just trying to think about mapping flags to a group of features and whether I do this myself.

Thanks for reading!

Gavin.

**Comment by hackvan** [comment]
Hi @ghenry

In the readme file in the [group gate section](https://github.com/tompave/fun_with_flags#group-gate) there are some useful examples about what I think you need to do.

For example, you can implement the protocol for your actor table and custom per flag (if you have a premium flag boolean defined on the user) or per group, you just need to specify or call the logic here on how you can identify a premium actor:

```elixir
defmodule MyApp.Actor do
  defstruct [:email, premium: false, groups: []]
end

defimpl FunWithFlags.Group, for: MyApp.Actor do
  def in?(%{premium: is_premium}, "is_premium"), do: !!is_premium
  def in?(%{groups: list}, group_name), do: group_name in list
end

elisabeth = %MyApp.Actor{email: "elisabeth@actor.com", premium: true, groups: ["premium", "free"]}
another = %MyApp.Actor{email: "another@actor.com", premium: false, groups: ["free"]}
FunWithFlags.Group.in?(elisabeth, "is_premium")
true
FunWithFlags.Group.in?(elisabeth, "premium")
true
FunWithFlags.Group.in?(another, "is_premium")
false
FunWithFlags.Group.in?(another, "premium")
false
```

Hope it works for you!

**Comment by ghenry** [comment]
Thanks! I did work it out in the end using your docs. Similar to that and
the Stripe webhooks update the flags automatically when a customer switches
plans to things like tester_plan for_actor etc.

**Comment by ghenry** [comment]
I'll show you here once I make this public on launch
https://github.com/SentryPeer/SentryPeerHQ

**Comment by ghenry** [comment]
Ending up keeping it simple:

https://github.com/SentryPeer/SentryPeerHQ/blob/main/lib/sentrypeer/plans.ex#L113

https://github.com/SentryPeer/SentryPeerHQ/blob/main/lib/sentrypeer/auth/auth0_user.ex

https://github.com/SentryPeer/SentryPeerHQ/blob/main/lib/sentrypeer_web/components/navigation_components.ex#L109

https://github.com/SentryPeer/SentryPeerHQ/blob/main/lib/sentrypeer_web/stripe_handler.ex#L93

Works well.

**Comment by tompave** [comment]
Apologies for the late reply, and I'm glad that you could sort it out.
