### ISSUE TITLE
mix release issue using Elixir 1.15.0

### ISSUE THREAD

**Issue by phiilu** [tompave/fun_with_flags#157]
When running `mix release` using Elixir 1.15.0 I get the error `** (Mix) Could not find application :table`.  

This is my `project` definition in my `mix.exs`: 

```Elixir
  def project do
    [
      app: :my_app,
      version: "0.1.0",
      elixir: "~> 1.15",
      elixirc_paths: elixirc_paths(Mix.env()),
      start_permanent: Mix.env() == :prod,
      aliases: aliases(),
      deps: deps(),
      releases: [
        my_app: [
          applications: [
            fun_with_flags: :load
          ]
        ]
      ]
    ]
  end
```

And the `deps`  for `fun_with_flags` are configured like this: 

```Elixir
{:fun_with_flags_ui, "~> 0.8", runtime: false},
{:fun_with_flags, "~> 1.10.1", runtime: false},
```

I am pretty lost with this error message, but this is related to fun_with_flags because if I remove the `fun_with_flags: :load` in the releases definition it runs just fine.

**Comment by sezaru** [comment]
I have the same issue, but for me it shows `** (Mix) Could not find application :myxql`

**Comment by phiilu** [comment]
Elixir 1.5.1 seems to fix this for me 🎉
