### ISSUE TITLE
Next release and Elixir 1.15 support

### ISSUE THREAD

**Issue by axelson** [tompave/fun_with_flags#162]
There's currently many nice fixes in the unreleased 1.11, so I'd like to put in a vote for cutting the next release soon :smiley: 

Also in the 1.11 I see "Add support for Elixir 1.15". Is there something specific about 1.10.1 that doesn't work on Elixir 1.15? I've been running fun_with_flags on Elixir 1.15 for a few weeks now and haven't noticed any issues (although maybe there's something I missed!)

**Comment by tompave** [comment]
Hey there.
Yes, that was long overdue. I've now published the new version: https://hex.pm/packages/fun_with_flags/1.11.0

> Also in the 1.11 I see "Add support for Elixir 1.15". Is there something specific about 1.10.1 that doesn't work on Elixir 1.15? I've been running fun_with_flags on Elixir 1.15 for a few weeks now and haven't noticed any issues (although maybe there's something I missed!)

Usually the library works with newer versions of Elixir and OTP without issues. There might be some compiler warnings [here](https://github.com/tompave/fun_with_flags/pull/158/files#diff-0c00433169ca7d88c043f54f2d8058f2798db9d9845956ec8700a3e1460dce62R28) and [there](https://github.com/tompave/fun_with_flags/pull/158/files#diff-629f73fde0ca4a4df85918b18bf0d3a5c500d34ff031d9a6a323a7e1f68c743bR223), but it doesn't stop working. When I update the Elixir and OTP versions in the changelog [and mix file](https://github.com/tompave/fun_with_flags/blob/82eda7d3fd89558b6a96b2eeeb40b690807b4358/mix.exs#L11), it's really a way to communicate which versions are supported. For example, with the just released `v1.11.0`, I won't be accepting reports for bugs that only happen with Elixir 1.12, but I'll investigate bug that happen with Elixir 1.13 and above.

**Comment by axelson** [comment]
Thanks for the release and the explanation! That makes sense :+1:
