### ISSUE TITLE
Feature time based flags

### ISSUE THREAD

**Issue by mohammedzeglam-pg** [tompave/fun_with_flags#185]
Flags enabled and disabled based on time or timezone

**Comment by probably-not** [comment]
This can be done with just a simple Group implementation. Something along the lines of:

```elixir
defmodule UserWithATimeZone do
  defstruct details: %{}, time_zone: "Etc/UTC"
end

defimpl FunWithFlags.Group, for: UserWithATimeZone do
  def in?(%UserWithATimeZone{time_zone: time_zone}, time_zone), do: true
  def in?(_user, _time_zone), do: false
  end
```

**Comment by tompave** [comment]
Indeed, this can be accomplished with one of the existing gates. "Actor" and "Group" are flexible tools, and they can be anything you want. You could even have a "timezone actor", if you wanted.
