### ISSUE TITLE
Web UI

### ISSUE THREAD

**Issue by fbjork** [tompave/fun_with_flags#2]
Any plans on adding a simple Web UI to this project?

I would suggest creating the web UI as part of this project for ease of setup.

**Comment by tompave** [comment]
Hi @fbjork, thanks for the suggestion. That's actually the next thing on the roadmap, and I'm currently working on it.

It's a Plug that can either run stand-alone or embedded in a Phoenix app.

**Comment by tompave** [comment]
To keep the number of dependencies low, it will be a different hex package though.

**Comment by tompave-roo** [comment]
Closing this as it's being worked on.

**Comment by tompave** [comment]
Closing this as it's being worked on.

**Comment by tompave** [comment]
Update: https://github.com/tompave/fun_with_flags_ui
