### ISSUE TITLE
Exception when using Ecto for persistence without cache

### ISSUE THREAD

**Issue by tomtaylor** [tompave/fun_with_flags#35]
I set up FunWithFlags with the following config. (I'm running a low volume site on a single node, and was happy to take the performance hit to not have to set up Redis.)

```elixir
config :fun_with_flags, :cache, enabled: false
config :fun_with_flags, :cache_bust_notifications, enabled: false

config :fun_with_flags, :persistence,
  adapter: FunWithFlags.Store.Persistent.Ecto,
  repo: Poplar.Repo
```
It worked absolutely fine in dev, but when I deployed to production (compiled into a release) I got the following exception on boot:

```
13:26:29.420 [info] Application fun_with_flags exited: exited in: FunWithFlags.Application.start(:normal, [])
** (EXIT) an exception was raised:
** (UndefinedFunctionError) function FunWithFlags.Store.Persistent.Redis.worker_spec/0 is undefined (module FunWithFlags.Store.Persistent.Redis is not available)
FunWithFlags.Store.Persistent.Redis.worker_spec()
(fun_with_flags) lib/fun_with_flags/application.ex:16: FunWithFlags.Application.children/0
(fun_with_flags) lib/fun_with_flags/application.ex:10: FunWithFlags.Application.start/2
(kernel) application_master.erl:277: :application_master.start_it_old/4
```

Is this a problem with my configuration, or have I hit a bug in the library? Thanks!

**Comment by tomtaylor** [comment]
I should probably add that my production releases use Distillery 2.0.12. I'm trying to diagnose this, but I'm confused why it's not picking up the correct module. My `config.script` in my release contains the following, which suggest it's picking up the Ecto module at compile time correctly, but incorrectly referencing the Redis module at runtime. Is anyone else using FunWithFlags in a Distillery 2.0 release?

```
     {apply,
         {application,load,
             [{application,fun_with_flags,
                  [{description,
                       "FunWithFlags, a flexible and fast feature toggle library for Elixir.\n"},
                   {vsn,"1.2.1"},
                   {id,[]},
                   {modules,
                       ['Elixir.FunWithFlags','Elixir.FunWithFlags.Actor',
                        'Elixir.FunWithFlags.Actor.Percentage',
                        'Elixir.FunWithFlags.Application',
                        'Elixir.FunWithFlags.Config',
                        'Elixir.FunWithFlags.Flag','Elixir.FunWithFlags.Gate',
                        'Elixir.FunWithFlags.Gate.InvalidGroupNameError',
                        'Elixir.FunWithFlags.Gate.InvalidTargetError',
                        'Elixir.FunWithFlags.Group',
                        'Elixir.FunWithFlags.Group.Any',
                        'Elixir.FunWithFlags.Notifications.PhoenixPubSub',
                        'Elixir.FunWithFlags.NullEctoRepo',
                        'Elixir.FunWithFlags.SimpleStore',
                        'Elixir.FunWithFlags.Store',
                        'Elixir.FunWithFlags.Store.Cache',
                        'Elixir.FunWithFlags.Store.Persistent',
                        'Elixir.FunWithFlags.Store.Persistent.Ecto',
                        'Elixir.FunWithFlags.Store.Persistent.Ecto.Record',
                        'Elixir.FunWithFlags.Store.Serializer.Ecto',
                        'Elixir.FunWithFlags.Store.Serializer.Redis',
                        'Elixir.FunWithFlags.Timestamps']},
                   {registered,[]},
                   {applications,[kernel,stdlib,logger,elixir]},
                   {included_applications,[]},
                   {env,[]},
                   {maxT,infinity},
                   {maxP,infinity},
                   {mod,{'Elixir.FunWithFlags.Application',[]}}]}]}},
```

**Comment by tomtaylor** [comment]
OK, I've managed to track this down. I'll explain for anyone discovering this from the future. I was building my release in a Dockerfile, including this line:

```dockerfile
COPY mix.exs mix.lock ./
RUN mix do deps.get, deps.compile
COPY . .
RUN mix do compile
```

This was copying the `mix.*` files, building the dependencies first, then copying and building the rest of the app. This made it more efficient, because it would only rebuild the dependencies if `mix.*` had changed. 

But, I think building the dependencies without the application's config files being present was causing FunWithFlags to compile with the default config. I'm now doing the following, and it seems to work:

```dockerfile
COPY . .
RUN mix do deps.get, deps.compile, compile
```

**Comment by tompave** [comment]
Hi @tomtaylor, thanks for trying the package and for the detailed report!

I'm glad that you figured out how to get it to work, but I'll count this as yet another reason to remove the conditional compilation of modules. I thought it was a good idea for performance reasons, but it's just causing problems in these corner cases.

**Comment by tomtaylor** [comment]
Thanks @tompave - that sounds like a good idea. PS: thanks for making such a brilliant library - apart from this deployment/compilation issue, it's very nicely put together.

**Comment by tompave** [comment]
Another thing @tomtaylor:

> I set up FunWithFlags with the following config. (I'm running a low volume site on a single node, and was happy to take _the performance hit to not have to set up Redis._)
> ```elixir
> config :fun_with_flags, :cache, enabled: false
> config :fun_with_flags, :cache_bust_notifications, enabled: false
> ```
> (_emphasis_ added)

If this works for you that's great, but you could still enable the cache because it's an in-memory cache backed by an ETS table ([its config](https://github.com/tompave/fun_with_flags/blob/v1.2.1/lib/fun_with_flags/store/cache.ex#L9)). In other words, in case it wasn't clear, Redis is not used for the cache but as an alternative to Ecto+RDBMS.

Even with a TTL of just a few seconds, enabling the ETS cache could reduce your DB hits by orders of magnitude, in some cases. It was designed with this use case in mind:

```EEx
<ul>
  <%= for user <- @users do %>
    <li class="user">
      <%= if FunWithFlags.enabled?(:foo, for: user), do: "foo", else: "bar" %>
    </li>
  <% end %>
</ul>
```

With your current config it would perform a DB queries for each iteration (what if you have hundreds users? 😱). With the cache enabled it would look up the flag data only once.

If you want to reduce any useless overhead when running on a single node, then you've already correctly disabled the cache-busting notifications. That means that [no notification worker is started](https://github.com/tompave/fun_with_flags/blob/v1.2.1/lib/fun_with_flags/application.ex#L30) and that [no notifications are emitted](https://github.com/tompave/fun_with_flags/blob/v1.2.1/lib/fun_with_flags/store/persistent/ecto.ex#L173).

**Comment by tomtaylor** [comment]
Ah ha! Thank you. Am I correct in thinking that without cache bust notifications enabled (using Redis), it'll take up to the length of the cache TTL before feature flag changes become active?

**Comment by tompave** [comment]
> Am I correct in thinking that without cache bust notifications enabled (using Redis), it'll take up to the length of the cache TTL before feature flag changes become active?

Not if you're on a single node. When a flag is created, updated or deleted, the ETS cache of the local node where the action is performed is [immediately updated](https://github.com/tompave/fun_with_flags/blob/v1.2.1/lib/fun_with_flags/store.ex#L37). The cache-bust notifications are there just to bust the cache on the other nodes.

What you describe would happen if you run without cache-bust notifications _on multiple nodes_. In that case the ETS cache would be updated immediately on the node where a flag is changed, but the other nodes would have to wait for the TTL to elapse. A couple of thoughts:

1. There is no guarantee that TTLs will be in sync on all nodes, and actually it's very likely that they won't. So when a flag is changed on one node, on another node the TTL could be 60s, and on another 0.5s.
2. As I mentioned even a low TTL could bring huge performance and load gains. So a TTL of 3-7s could mitigate this problem.

> using Redis

Another thing: if you're not using `redix` for persistence, then the cache-bust notifications will use Phoenix pubsub. That means wither clustered Erlang (with `pg2`) or indirectly `redix`.

**Comment by tomtaylor** [comment]
Brilliant - thank you!

**Comment by AndrewKlymchuk** [comment]
@tompave, conditional compilation ruins my cache when I use docket during deploy to cloud because of the same issue. It will be great to disable it, or make it optional depending from env variable.
