### ISSUE TITLE
Support for custom table names

### ISSUE THREAD

**Issue by zakjholt** [tompave/fun_with_flags#62]
right now, it seems like the [table name is hardcoded to "fun_with_flags_toggles"](https://github.com/tompave/fun_with_flags/blob/3b5a1c88436fd739858051268f9af298fc0337ae/lib/fun_with_flags/store/persistent/ecto/record.ex). It'd be nice to be able to use a different name

**Comment by tompave** [comment]
Hello, and thank you for opening this issue.

Do you have any use case in mind where customizing the table name would be useful?

I'd rather avoid adding extra complexity to the (configuration) API or the internals of the package without a valid reason.

**Comment by tompave** [comment]
I have closed the PR because I haven't received a response in more than a week.

If you still feel that this is a worthwhile addition, and you can describe a use case where it would be useful, please add a comment to this issue.

**Comment by brandonjoyce** [comment]
I think this feature would be useful.  Without it I may have to fork the project to use it because my DBAs hold the keys for table names and have the ultimate say.  As much as I like the name "fun_with_flags", it might not meet everyone's naming standards.  Especially in a more tightly controlled database environment.

**Comment by tompave** [comment]
Hi @brandonjoyce, thank you for that comment. That makes a lot of sense.

I've seen https://github.com/tompave/fun_with_flags/pull/63#issuecomment-596738096. If you'd like to give this a go, please go ahead!

**Comment by tompave** [comment]
Hi @brandonjoyce, looks like @BobbyMcWho has issued a PR for this 30 minutes after my comment above. Do you guys know each other, or have you worked together?

**Comment by BobbyMcWho** [comment]
Hi @tompave, @brandonjoyce and I are on the same team 😀

**Comment by tompave** [comment]
Ok, fair enough! I just wanted to make sure @brandonjoyce was ok with this, since he took the initiative to start this again and convince me it would be useful.

**Comment by tompave** [comment]
This has now been released with version v1.5.0: https://hex.pm/packages/fun_with_flags/1.5.0
