### ISSUE TITLE
Support Phoenix PubSub 2.0

### ISSUE THREAD

**Issue by dmorneau** [tompave/fun_with_flags#69]
Phoenix 1.5.0-rc0 is now out with Phoenix PubSub 2.0, however fun_with_flags currently depends on phoenix_pubsub "~> 1.0".

**Comment by tompave** [comment]
Thank you for bringing this up.

I'll bump the dependency in the new version of `fun_with_flags`.

**Comment by jc00ke** [comment]
This will make FWF compatible with Phoenix 1.5, yeah?

**Comment by tompave** [comment]
@jc00ke yes, it should

**Comment by tompave** [comment]
I don't think it's just about bumping the dependency in the mixfile. I also need to update it in the tests.

**Comment by tompave** [comment]
This has now been released with version v1.5.0: https://hex.pm/packages/fun_with_flags/1.5.0

**Comment by dmorneau** [comment]
Fantastic, thank you!
