### ISSUE TITLE
Non-boolean variations

### ISSUE THREAD

**Issue by garthk** [tompave/fun_with_flags#73]
G'day! Having already had to use at least one tri-state variation on our previous solution, I'm nervous about solving the same kind of problem by strapping together FWF's boolean flags. All off is fine, but >1 on would be confusing.

Don't suppose we could support any atom, not just `:true` and `:false`? It'd need an Ecto migration to migrate that boolean `enabled` to a string `state`… what else?

**Comment by tompave** [comment]
Hello,

I'm afraid that non-boolean flag values are not supported, by design. What you describe should be modelled with multiple flags.

Why do you think it would be confusing?
