### ISSUE TITLE
Usage with PostgresSQL schemas

### ISSUE THREAD

**Issue by LeandroLM** [tompave/fun_with_flags#83]
I have a Phoenix Umbrella project with a bunch of apps using PostgreSQL. Each app is configured with a [@schema_prefix](https://hexdocs.pm/ecto/Ecto.Schema.html#module-schema-attributes) schema attribute so that they can all access the same database, but using different schemas. That way I can keep each app's data logically separated from the others, without the need to create multiple databases in the same PostgreSQL instance, for example.

However, when I try do use `FunWithFlags` within one of these apps, the lib tries to find the table on the default `public` schema, and of course, it can't find it and it errors out. Is there a way to configure this in `FunWithFlags`? I've tried a few things like including the schema name in the option `ecto_table_name`, but with no success.

**Comment by tompave** [comment]
Hello, and thank you for opening the issue.

I don't think that schemas are supported at the moment.

My recommendation is to fork [the Ecto adapter](https://github.com/tompave/fun_with_flags/blob/master/lib/fun_with_flags/store/persistent/ecto.ex) in your application and try to add support for the schemas. You can configure your custom adapter with [these instructions](https://github.com/tompave/fun_with_flags#custom-persistence-adapters).

If it works, it sounds like an opportunity for a PR :-)

**Comment by LeandroLM** [comment]
Thanks for the response @tompave ! On second thought, we decided to use the public schema following some conventions to avoid conflicts, but I'll try doing as you suggest when I have some time. If it works, I'll open a PR 🙂
